src/views/repository/content/BasesForm.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
When the user clicks to activate Brain, they are redirected to the tunings tab, but the appearance of the selected tab is not changed.
* Uses UnnnicTab `activeTab` prop to use reactive selected tab.
=> [Nexus-1515] Bug: Selected Tab is not Reactive

src/components/actions/ModalActions.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Fixes the template for flows list with two per line.
=> [Nexus-1523] Bug: Flows List with Only One Per Line Instead of Two

src/components/intelligences/IntelligencesFilter.vue, src/components/intelligences/__tests__/IntelligencesFilter.unit.spec.js, src/views/Home.vue
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
To start the process of deprecating the content base, this was the first step, hiding the option of generative AIs for people who don't have any content base.
* Hides the option of generative AIs for people who have no content base;
* Adds unit test for `IntelligencesFilter.vue`.
=> [Nexus-1744] Process of Deprecating the Content Bases: Hide List Filter Option

src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/views/repository/content/BasesFormFiles.vue, src/views/repository/content/__tests__/BasesFormFiles.unit.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Visual feedback to the user when there is an error with the file format and size.
* Adds verification of file format and size.
=> [Nexus-1583] Content Base Files: Error Alert for Unsupported Files and Files That Exceed the Size Limit

src/utils/HotjarIdentifyUser.js, src/utils/__test__/HotjarIdentifyUser.unit.spec.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Sends the correct auth token to Keycloak user info.
=> [Nexus-1774] Bug: Send the Correct Auth Token to Keycloak User Info

src/__tests__/components/actions/ModalChangeAction.spec.js, src/api/nexus/Actions.js, src/components/Brain/ContentBase/ContentItem.vue, src/components/Brain/ContentBase/__tests__/ContentItem.spec.js, src/components/actions/ModalChangeAction.vue, src/views/Brain/RouterActions.vue
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Some commerce users do not have permission to create and edit new actions in the agent builder.
- Removed delete action button depends by action is editable and tests;
=> [NEXUS-2065] - Disable actions by user perm

src/components/Brain/ContentBase/ModalAddSite.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
When adding a content url, it was not identified as valid if there was a hyphen in the domain.
- Replaced ModalAddSite regex at valid url function.
=> [NEXUS-2114] - Accept hyphen in content url domain

config.js.tmpl, public/config.js, src/components/repository/CreateRepository/CreateIntelligenceModal.vue, src/store/auth/state.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Some orgs needed access to content creation AIs.
- Enable content AI creation for specific orgs;
- Added `VITE_ORGS_CAN_CREATE_CONTENT_AI` var env.
=> [NEXUS-2151] - Defined orgs can create content AI

src/components/Brain/ContentBase/ModalAddSite.vue, src/components/Brain/ContentBase/__tests__/ModalAddSite.spec.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
When users added content URLs with spaces at the beginning or end, the validator did not identify this as an invalid URL and requested it as such, generating an error in the request.
A function that removes all spaces from the URL in ModalAddSite, triggered by the input event, has been added.
A test for this functionality has also been added.
=> [NEXUS-2160] - Fix spaces at content URLs

src/api/nexus/Actions.js, src/components/actions/steps/SelectFlow.vue, src/components/actions/steps/__tests__/SelectFlow.unit.spec.js, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- Removed blocking of only one stream per action;
- Added tooltip and count of actions by flow;
- Added tests to SelectFlow actions count and tooltip;
- [Modal select action flow](https://www.figma.com/design/5E67hPt0HlCDckwCtnn1HR/Brain-Vision?node-id=466-4744&m=dev)
=> [NEXUS-2161] - Multiple actions per flow

src/views/Brain/RouterActions.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
When editing an action, the flow name was not recognized due to a change in the object returned by the request.
Changed key in RoutecActions so that action editing recognizes the right uuid of the flow and gets its name.
Bug before this fix:
=> [NEXUS-2227] - Fix "Flow name unavailable" with multiple flows per action

src/__tests__/components/actions/ModalChangeAction.spec.js, src/components/actions/ModalChangeAction.vue, src/views/Brain/RouterActions.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Users are unable to edit an action due to the wrong uuid that the application is passing to the api.
Adjusted uuid passed to the api when trying to save an action.
=> [NEXUS-2230] - Hotfix ModalChangeAction save

src/components/repository/home/HomeRepositoryCard.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Users were unable to access the dropdown triggered by the more actions button on the intelligence listing card, being redirected when clicking on it.
Added a stopPropagation when clicking the more actions button.
=> [NEXUS-2242] - Fix of IA repository card more actions button

src/components/Brain/Monitoring/ResponseSuccessGroundedness/TextSentences.vue, src/components/Brain/Monitoring/ResponseSuccessGroundedness/__tests__/TextSentences.spec.js, src/components/Brain/Monitoring/ResponseSuccessGroundedness/__tests__/__snapshots__/TextSentences.spec.js.snap
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Improve the visualization of details for each sentence of the monitored response.
- Added tooltip in each monitored sentence with source name and response reliability;
- Added increased outline-thickness when hovering over the sentence.
- [Design File 1](https://www.figma.com/design/5E67hPt0HlCDckwCtnn1HR/Brain-Vision?node-id=1590-7112&m=dev)
=> [NEXUS-2320] - Monitoring inspect sources tooltip

src/__tests__/views/Brain/RouterMonitoring/index.spec.js, src/store/Monitoring.js, src/views/Brain/RouterMonitoring/index.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
A new Websocket connection was made each time the monitoring view was mounted, but the expected behavior is that there is only one connection.
Added variable in the monitoring store for the ws instance and added a validation to only connect to the websocket if that instance does not exist. Also added tests for this behavior.
=> [NEXUS-2317] - Fix monitoring websocket connect every mount

src/views/repository/content/Tests.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
An additional type in the preview response was added and it was necessary to cover its expected behavior.
Added behavior to remove the last message if the response type is `cancelled`
=> [NEXUS-2371] - Added preview cancelled type behavior

src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/views/Brain/Brain.vue, src/views/ContentBases/components/FilePreviewNotFound.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Files added to projects that use Bedrock do not have their content available through the backend, so it was necessary to change the informational message for this case.
Changed the icon and description of the newsletter when the project's `indexer_database` is equal to `bedrock`
=> [NEXUS-2397] - Fix Bedrock not found content detail message

src/views/Brain/RouterCustomization.vue
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Users could add infinite empty instructions, so to improve the UI the rule for adding a new instruction was changed.
- Changed the icon for deleting instructions to follow the pattern of the rest of the application.
- Added a rule to disable the button for adding a new instruction if the last one is empty.
=> [NEXUS-2428] - Adjusted add instruction button only if last instruction has value

src/__tests__/integration/brain.integration.test.js, src/views/Brain/RouterProfile/RouterProfileGeneralInfo.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
At old projects, the profile personality field is calling a nonexistent translation, like the demonstration.
- Removed nonexistent placeholder in the profile personality field.
=> [NEXUS-2554] - Fix of profile personality field value

src/components/Brain/BrainHeader.vue, src/views/Brain/Brain.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Until the design for the preview on other screens besides the agents team, for better user experience it was required to remove the preview from the other tabs
- Removed preview of tabs that are not agents team.
=> [NEXUS-2605] Removed preview outside agents team tab

src/__tests__/views/Brain/RouterAgentsTeam/ActiveTeam.spec.js, src/__tests__/views/Brain/RouterAgentsTeam/RouterAgentsTeam.spec.js, src/__tests__/views/Brain/RouterAgentsTeam/__snapshots__/ActiveTeam.spec.js.snap, src/__tests__/views/Brain/RouterAgentsTeam/__snapshots__/RouterAgentsTeam.spec.js.snap, src/components/Brain/BrainHeader.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/store/AgentsTeam.js, src/views/Brain/RouterAgentsTeam/ActiveTeam.vue, src/views/Brain/RouterAgentsTeam/index.vue
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
A UI improvement to the agent team view was needed before the release of Agent Builder 2.0
- Reorganize RouterAgentsTeam component layout and remove AgentsGallery;
- Add agents gallery handler to BrainHeader and improve responsiveness of actions;
- Updated ActiveTeam design;
- Add agents gallery trigger to ActiveTeam component.
- [New agents team design](https://www.figma.com/design/FGfl8EmJCNMz45TX1s3XQO/Agents-Builder-2.0?node-id=1844-7894&m=dev)
=> [NEXUS-2682] - New agents team view

src/__tests__/api/nexus/monitoring.unit.spec.js, src/__tests__/views/Brain/Brain.spec.js, src/__tests__/views/Brain/RouterAgentsTeam/ActiveTeam.spec.js, src/__tests__/views/Brain/RouterMonitoring/ReceivedMessages.spec.js, src/__tests__/views/Brain/RouterMonitoring/ReceivedMessagesHistoryQuestionAndAnswer.spec.js, src/api/nexus/Monitoring.js, src/components/Brain/Preview/PreviewDetails.vue, src/components/Brain/Preview/__tests__/PreviewDetails.spec.js, src/components/Brain/PreviewLogs.vue, src/components/Brain/__tests__/PreviewLogs.spec.js, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/store/Monitoring.js, src/utils/Growthbook.js, src/views/Brain/Brain.vue, src/views/Brain/RouterAgentsTeam/ActiveTeam.vue, src/views/Brain/RouterMonitoring/RouterMonitoringReceivedMessages/index.vue, src/views/Brain/RouterMonitoring/RouterMonitoringReceivedMessagesHistory/MessageContext.vue, src/views/Brain/RouterMonitoring/RouterMonitoringReceivedMessagesHistory/QuestionAndAnswer.vue, src/views/Brain/RouterMonitoring/RouterMonitoringReceivedMessagesHistory/index.vue, src/views/Brain/RouterMonitoring/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
In order for Agent Builder 2.0 users to have an initial tracking of the agent's messages, it was necessary to add the message traces to the supervisor.
- Changed the PreviewLogs component to receive logs via props instead of getting them directly from the store;
- Added the trace request for Agent Builder 2.0 supervisor messages;
- Temporarily removed the Agent Builder 2.0 Supervisor performance session;
- Adjusted the QuestionAndAnswer component to have the show/hide logs functionality.
=> [NEXUS-2754] - Supervisor of Agent Builder 2.0 

src/views/Brain/RouterTunings.vue
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
The deployment of the Agent Builder 2.0 progressive feedback field backend has been delayed, so the frontend is not working yet.
- Update tunings tabs logic based on agents team feature flag
=> [NEXUS-2862] - Removed temporaly Agent Builder 2.0 settings tab at Tuning view

src/components/Brain/Preview/PreviewDrawer.vue, src/components/Brain/Preview/__tests__/PreviewDrawer.spec.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
In Agent Builder 2.0, the preview clear conversations button is not working.
Instead of updating the component's key as was done before, after the preview refactoring, the clear now needs to be done in the store.
=> [NEXUS-2885] - Fix preview clear conversations

src/components/Brain/AgentsTeam/AssignAgentCard.vue, src/store/AgentsTeam.js, src/store/__tests__/AgentsTeam.unit.spec.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The assignment and removal of agents in the team needed to be modified in the frontend due to structural changes in the backend, which no longer uses `external_id`
Updated toggleAgentAssignment to use `uuid` instead of `external_id`
=> [NEXUS-2878] - Update toggleAgentAssignment to use uuid instead of external_id

src/components/Brain/Preview/PreviewDrawer.vue, src/components/Brain/Preview/__tests__/PreviewDrawer.spec.js, src/views/repository/content/Preview.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Whenever the agent builder 2.0 preview was closed, the agent lost the context, but the messages remained on the screen. 
Added a validation to only send a new urn to the request (which changes the context), if the user clicks on "clear conversations".
=> [NEXUS-2903] Fix preview context persistence

src/api/nexus/AgentsTeam.js, src/components/Brain/PreviewLogs.vue, src/components/Brain/__tests__/PreviewLogs.spec.js, src/components/Brain/__tests__/__snapshots__/PreviewLogs.spec.js.snap, src/store/AgentsTeam.js, src/views/AgentBuilder/AgentsTeam/AgentsGalleryModal.vue, src/views/AgentBuilder/__tests__/AgentsTeam/AgentsGalleryModal.spec.js, src/views/AgentBuilder/index.vue, src/views/repository/content/Preview.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
This PR addresses several issues found in the preview experience:
- Crashes when assigning a newly pushed agent.
- Missing agent identification in logs after an agent is removed from the team.
- Some logs showing without agent identification.
- Input text in the preview being overlapped by the send icon.
- Fixed a crash in the preview when assigning a pushed agent.
- Adjusted the input padding in the Preview component to prevent text from being hidden behind the send icon.
- Added validation for agent names received through `invocationInput` to ensure proper identification in logs.
- Updated PreviewLogs to accept an …
=> [NEXUS-2971] - Fix preview logs bugs

src/api/nexusaiAPI.js, src/components/Brain/AgentsTeam/AssignAgentDrawer.vue, src/components/Brain/AgentsTeam/__tests__/AssignAgentDrawer.spec.js, src/store/Tunings.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Credentials were not being created when there was already another agent assigned to the project.
- Removed unnecessary parameter from `/credentials` `POST`
- Adjusted the logic and call for creating credentials and adjusted the tests for this new logic.
=> [NEXUS-2993] - Fix Agent Builder 2.0 credentials creation

src/__tests__/api/nexus/Supervisor.spec.js, src/api/nexus/Supervisor.js, src/store/Supervisor.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The Supervisor 2.0 conversations endpoint parameters needed to be changed to follow the new API standard.
Removed unused 'end' parameter from getById and streamline date formatting in loadConversations and adjusted tests to works with this logic.
=> [NEXUS-3007] - Fix Supervisor 2.0 conversations params

src/websocket/listeners/index.js, src/websocket/listeners/preview/index.js, src/websocket/listeners/preview/update.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
To include more than one answer per question in the Agent Builder 2.0 preview
Added preview message listener on websocket connection and integration of responses based on that.
=> [NEXUS-3106] - Agent Builder 2.0 preview messages via websocket

src/components/Markdown.vue
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
To better the UX, `mailto:` prefix and link are been removed from preview.
Remove 'mailto:' prefix from email links in markdown renderer
=> [NEXUS-3185] - Remove 'mailto:' prefix from email links in preview

src/views/AgentBuilder/Supervisor/SupervisorConversations/ConversationsTable/ConversationInfos.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Some numbers with different country codes from Brazil were being formatted as if they were.
=> hotfix: Update Supervidor WhatsApp URN validation to require 12 digits

src/utils/previewLogs.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
It was necessary to implement trace type handling to support the format already sent by the backend. This way, processing now recognizes and handles traces arriving with the previously defined type.
Added expected types in the `previewLogs` utility to map and process traces according to their respective types.
=> [NEXUS-3564] - Log processing handling trace types
