weni-ai/intelligence-webapp

public/config.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
remove use boto-1 on brain
remove boto-1 option
=> [NEXUS-1422] removing boto-1 option

src/components/RightSidebar.vue, src/views/repository/content/BasesForm.vue, src/views/repository/content/BasesFormFilesItem.vue, src/views/repository/content/BasesFormText.vue, src/views/repository/content/Tests.vue, src/views/repository/content/router/ModalSaveChangesError.vue, src/views/repository/content/router/RouterCustomization.vue
* * [X] Bugfix
* * [X] Code style update (formatting, local variables)
* * [ ] Tests
* * [ ] Other
- Adjustments design review
- update tab component
- update customization component
- update files/sites component
- update preview btn
- update error save changes modal
- [Design](https://www.figma.com/design/QE22CBVh18ORmxe1HhDUkD/Brain?m=dev&node-id=1264-5558)
=> [NEXUS-1421] adjustments design review

package.json, yarn.lock
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
update unnnic to use new components
update unnnic
=> [Nexus-1421] - update unnnic

src/store/brain/index.js, src/views/repository/content/BasesForm.vue, src/views/repository/content/router/Preview/FieldErrorRequired.vue, src/views/repository/content/router/RouterCustomization.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
The user wants to see which fields are required in the personalization tab.
* Adds customization required fields errors.
- [Brain - Personalização](https://www.figma.com/design/QE22CBVh18ORmxe1HhDUkD/Brain?node-id=1705-531&t=IKgfjvHlD5UMXqU3-4)
=> [Nexus-1382] Brain Customization Tab: Required Fields Errors

src/views/repository/content/BasesFormFiles.vue, src/views/repository/content/BasesFormFilesItem.vue
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
- improve file indexing flow
- added standardization in the progress component
- added additional error handling
=> [NEXUS-1420] - Add loading and error handling to the content base

package.json, src/App.vue, src/components/actions/ModalActions.vue, src/components/actions/ModalChangeAction.vue, src/main.js, src/store/user/actions.js, yarn.lock
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Changed Sentry setup;
* Fixed Brain Actions Modal Header styles.
=> [Nexus-1458] Change Sentry Setup

package.json, yarn.lock
* * [ ] Bugfix
* * [ ] Tests
* * [X] Other
-  update unnnic version
- update package.json and yarn.lock with new unnnic version
=> [NEXUS-1428] update unnnic version

src/api/nexusaiAPI.js, src/components/repository/CreateRepository/DefinitionsTab.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Removes/replaces depreciated components.
* Replaces UnnnicSelect to UnnnicSelectSmart component.
=> [Nexus-1439] Updates Depreciated Components

src/views/repository/content/BasesForm.vue, src/views/repository/content/BasesFormGenericListHeader.vue, src/views/repository/content/router/RouterCustomization.vue
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
- design review adjustments to match figma
- adjust spaces
- adjust title font color
- [Design File](https://www.figma.com/design/QE22CBVh18ORmxe1HhDUkD/Brain?m=dev&node-id=1264-13689)
=> [NEXUS-1499] Design review brain

src/components/LoadingFormElement.vue, src/components/repository/CreateRepository/CreateRepositoryForm.vue, src/views/repository/content/BasesFormFiles.vue, src/views/repository/content/BasesFormFilesItem.vue, src/views/repository/content/BasesFormText.vue, src/views/repository/content/router/RouterCustomization.vue, src/views/repository/content/router/RouterTunings.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
User feedback to know when data is being loaded.
* Adds Skeleton Loading to Customization tab.
=> [Nexus-1503] Skeleton Loading: Customization Tab

src/views/repository/content/BasesFormFiles.vue, src/views/repository/content/BasesFormFilesItem.vue
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
- Corrections and adjustments to the content base
- adjust logic of tooltips
- add logic correction to error files
=> [NEXUS-1500] Adjust tooltip and file error logic - Brain

src/store/brain/index.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Ignores customization tab required fields if it is not loaded.
=> [Nexus-1518] Bug: Wrong Save Button Disabled in Tunings

src/components/QuickTest/AnswerSources.vue
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
- bug fix in the response source
- correction to the line break in the answer font
=> [NEXUS-1524] correction to the line break in the answer font - Preview Brain

src/store/brain/index.js, src/views/repository/content/BasesForm.vue, src/views/repository/content/router/RouterCustomization.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
To avoid the initial error of required fields in customization tab, move the validation to after the user clicks the Save button.
* Implements lazy validation to customization tab.
=> [Nexus-1516] Customization Tab: Lazy Validation

src/utils/FlowPreview.js, src/views/repository/content/Tests.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Addition of URN generator to differentiate conversations from Preview, previously with a constant URN that did not generate independence of conversations.
* Adds dynamic URN generator.
=> [Nexus-1562] Preview: Dynamic URN based on Content Base Uuid and Random Digits

src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/views/repository/content/BasesFormFiles.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- remove gray alert that is not that interesting for the user
- remove default alert from content base
=> [NEXUS-1533] REMOVE DEFAULT ALERT CONTET BASE

src/views/Brain/Brain.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- Refactoring - Fix preview rendering correction in Brain
- Remove conditional preview rende
=> [Nexus-1581] Refactoring - Fix preview rendering correction

src/components/__tests__/actions/ModalChangeAction.spec.js, src/components/actions/ModalChangeAction.vue
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1602] - Test suite ModalChangeAction

src/components/Divider.vue, src/components/intelligences/IntelligencesPublicList.vue, src/components/repository/IntegrateButton.vue, src/components/repository/home/HomeRepositoryCard.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/views/Home.vue, src/views/repository/content/ContentItemActions.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Removes integrate button for generative intelligences.
=> [Nexus-1607] Remove Integrate Button for Generative Intelligences

.github/workflows/unit-tests.yaml, package.json, vitest.config.js, yarn.lock
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
- add config coverage
- change CI unit test
=> [NEXUS-1614]  Add coverage to unit tests  

src/api/nexusaiAPI.js, src/views/Brain/Brain.vue, src/views/Brain/RouterContentBase.vue, src/views/repository/content/BarAddSite.vue, src/views/repository/content/BasesFormFiles.vue, src/views/repository/content/BasesFormFilesItem.vue, src/views/repository/content/BasesFormSites.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Fixes infinite loading in adding site;
* Separates Add Site Right Sidebar into a separated component.
=> [Nexus-1596] Bug: Adding Site Cause an Infinite Loading

src/views/repository/content/BasesFormGenericListHeader.vue, src/views/repository/content/__tests__/BasesFormGenericListHeader.unit.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
* Adds BasesFormGenericListHeader.vue unit test.
=> [Nexus-1625] Test: BasesFormGenericListHeader.vue

src/__tests__/views/Brain/ModalSaveChangesError.spec.js, src/__tests__/views/Brain/RouterActions.spec.js, src/views/Brain/ModalSaveChangesError.vue
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [Nexus 1630] unit test - ModalSaveChangesError

src/__tests__/views/Brain/Preview/FieldErrorRequired.spec.js
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1635] unit test - FieldErrorRequired

src/__tests__/views/Brain/Preview/Placeholder.spec.js
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1636] unit test - Preview Placeholder

src/views/repository/content/BasesFormFilesItem.vue, src/views/repository/content/__tests__/BasesFormFilesItem.unit.spec.js
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
* Reverts commented code.
=> [Nexus-1639] File Preview: Revert the Temporarily Hidden

src/__tests__/views/Brain/RouterTuningsAdvanced.spec.js, src/views/Brain/RouterTuningsAdvanced.vue
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1631] Unit test: RouterTuningsAdvanced

src/views/repository/content/BasesFormGenericList.vue, src/views/repository/content/__tests__/BasesFormGenericList.unit.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
* Adds unit test for BasesFormGenericList.vue.
=> [Nexus-1624] Test: BasesFormGenericList.vue

src/views/repository/content/BarAddSite.vue, src/views/repository/content/BasesFormFiles.vue, src/views/repository/content/BasesFormFilesItem.vue, src/views/repository/content/BasesFormSites.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The user cannot remove site with error.
=> [Nexus-1648] Bug: Remove Site Options Wasn't Showed

src/components/actions/ModalActions.vue, src/views/Brain/RouterActions.vue
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
-  today it is not allowed to add 2 shares
- add new prop
- add filter
=> [NEXUS-1647]  Add filter to the actions modal

src/__tests__/views/Brain/RouterActions.spec.js, src/views/repository/content/__tests__/BasesFormGenericList.unit.spec.js
* * [x] Bugfix
* * [x] Tests
* * [ ] Other
* Fixes test with errors.
=> [Nexus-1649] Bug: Test with Errors

README.md
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Config Codecov in this repository.
- Adjusted Codecov badge;
- Updated Vue version at _Main Technologies_ session;
- Fix _Set up_ session to this repository.
=> [ENGAGE-1241] - Update README.md

src/__tests__/mocks/brainTuningsFields.js, src/__tests__/views/Brain/RouterTunings.spec.js, src/views/Brain/RouterTunings.vue
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [Nexus-1632] RouterTunings unit test

src/views/repository/content/BasesFormFiles.vue, src/views/repository/content/__tests__/BasesFormFiles.unit.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
* Adds unit test for `BasesFormFiles.vue`.
=> [Nexus-1623] Test: BasesFormFiles.vue

src/__tests__/views/Brain/RouterCustomization.spec.js, src/views/Brain/RouterCustomization.vue
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1628] RouterCustomization unit test

nginx.conf
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- Restricts content sources that the browser is authorized to load.
- add Content-Security-Policy (CSP) in nginx conf
=> [NEXUS 1616] [CFE 274] - ADD Content-Security-Policy (CSP)

src/views/Brain/Brain.vue, src/views/ContentBases/filesPagination.js, src/views/ContentBases/indexingProcess.js, src/views/ContentBases/sitesPagination.js, src/views/repository/content/BasesFormSites.vue, src/views/repository/content/__tests__/BasesFormSites.unit.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
* Adds unit test for `BasesFormSites.vue`;
* Moves the files and sites indexing process to a separate file for reasons of organization and reuse.
=> [Nexus-1626] Test: BasesFormSites.vue

src/api/nexusaiAPI.js, src/store/brain/index.js, src/views/Brain/Brain.vue, src/views/Brain/RouterContentBase.vue, src/views/ContentBases/Form.vue, src/views/repository/content/BasesFormText.vue, src/views/repository/content/__tests__/BasesFormText.unit.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
* Adds unit test for `BasesFormText.vue`.
=> [Nexus-1627] Test: BasesFormText.vue

src/store/brain/models.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- add new model openai
- adding gpt-4o-mini
=> [NEXUS-1677] add new option gpt-4o-mini

src/__tests__/components/PageContainer.spec.js, src/__tests__/views/Brain/Preview/Placeholder.spec.js, src/utils/plugins/i18n.js, src/views/ContentBases/components/FilePreviewNotFound.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Resolves CI problems that prevented tests from running.
=> [Nexus-1696] Fixes Broken CI

src/__tests__/api/auth.spec.js, src/__tests__/api/category.spec.js, src/__tests__/api/index.spec.js, src/__tests__/api/integration.spec.js, src/__tests__/api/nexusaiAPI.spec.js, src/__tests__/api/nexusaiRequest.spec.js, src/__tests__/api/repository.spec.js, src/__tests__/api/request.spec.js, src/__tests__/api/requestExternal.spec.js, src/__tests__/api/user.spec.js, src/__tests__/api/utils/forceHttps.spec.js, src/__tests__/api/utils/index.spec.js, src/__tests__/api/utils/page.spec.js, src/__tests__/api/v2/repository.spec.js, src/api/nexusaiAPI.js, src/api/nexusaiRequest.js, src/api/utils/forceHttps.js
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1658] - ADD API UNIT TESTS

src/__tests__/views/Brain/RouterPreviewFullPage.spec.js, src/views/Brain/RouterPreviewFullPage.vue, src/views/repository/content/Tests.vue
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1661] - add unit tests RouterPreviewFullPage

src/__tests__/components/PageContainer.spec.js, src/__tests__/views/Brain/Preview/ModalPreviewQRCode.spec.js, src/__tests__/views/Brain/Preview/Placeholder.spec.js, src/utils/plugins/i18n.js, src/views/Brain/Preview/ModalPreviewQRCode.vue, src/views/ContentBases/components/FilePreviewNotFound.vue
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1662] - Add unit test - ModalPreviewQRCode

src/__tests__/store/auth/actions.spec.js, src/__tests__/store/auth/getters.spec.js, src/__tests__/store/auth/mutations.spec.js, src/__tests__/store/brain/index.spec.js, src/__tests__/store/cached-fetch/actions.spec.js, src/__tests__/store/cached-fetch/getters.spec.js, src/__tests__/store/cached-fetch/mutations.spec.js, src/__tests__/store/category/actions.spec.js, src/__tests__/store/integration/actions.spec.js, src/__tests__/store/integration/mutations.spec.js, src/__tests__/store/news/actions.spec.js, src/__tests__/store/news/getters.spec.js, src/__tests__/store/repository/actions.spec.js, src/__tests__/store/repository/getters.spec.js, src/__tests__/store/repository/mutations.spec.js, src/__tests__/store/user/actions.spec.js, src/__tests__/store/user/getters.spec.js, src/__tests__/store/user/mutations.spec.js, src/store/brain/index.js, src/utils/watchOnce.js
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1663] Add store unit tests

src/views/repository/content/BarAddSite.vue, src/views/repository/content/__tests__/BarAddSite.unit.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
* Adds the `BarAddSite.vue` test component.
=> [Nexus-1656] Test: BarAddSite.vue

config.js.tmpl, src/__tests__/components/actions/ModalChangeAction.spec.js, src/__tests__/views/Brain/RouterActions.spec.js, src/api/nexusaiAPI.js, src/components/actions/ModalChangeAction.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/views/Brain/RouterActions.vue
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Improves the interface when editing an action.
* Adds the new design for editing actions.
- [Brain - Ações v2](https://www.figma.com/design/QE22CBVh18ORmxe1HhDUkD/Brain?node-id=2347-8814&m=dev)
=> [Nexus-1690] Redesign: Action Editing

src/__tests__/components/actions/ModalActions.spec.js, src/api/nexusaiAPI.js, src/components/actions/ModalActions.vue, src/components/actions/steps/NominateAction.vue, src/components/actions/steps/__tests__/NominateAction.unit.spec.js, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/views/repository/content/BarAddSite.vue, src/views/repository/content/__tests__/BarAddSite.unit.spec.js
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
- new logic suggested names in action
- adding new integration with suggested names
=> [NEXUS-1672] - Modal action integration with suggested names

src/__tests__/components/actions/ModalActions.spec.js, src/components/actions/ModalActions.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
- improved stock name generation
- add translations
=> [NEXUS-1725] - Translation adjustments in the stock name generator

src/components/ModalWarn.vue, src/components/__tests__/ModalWarn.unit.spec.js, src/components/repository/IntegrateButton.vue, src/components/repository/__tests__/IntegrateButton.unit.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
* Adds unit tests for `IntegrateButton.vue` and `ModalWarn.vue`.
=> [Nexus-1712][Nexus-1714] Tests: ModalWarn.vue and IntegrateButton.vue

src/components/actions/steps/Describe.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
* Changes Describe Action translations.
=> [Nexus-1740] Change Describe Action Translations

src/locales/en.json, src/locales/es.json, src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- adjust translation not validated
- adjusting translations
=> [NEXUS-1741] Adjusting the translation of names in actions

src/components/repository/CreateRepository/CreateRepositoryForm.vue, src/components/repository/CreateRepository/IntelligenceTab.vue, src/components/repository/CreateRepository/__tests__/IntelligenceTab.spec.js
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1702] - Add IntelligenceTab unit test

src/__tests__/views/Brain/Brain.spec.js, src/views/Brain/Brain.vue
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
- adjusting flow variables
=> [NEXUS-1721] ADD Brain unit test

src/__tests__/views/Brain/RouterContentBase.spec.js, src/views/repository/content/BasesFormText.vue
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1720] Add RouterContentBase unit test

src/components/BaseSettingsForm.vue, src/components/__tests__/BaseSettingsForm.unit.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
* Adds unit test for `BaseSettingsForm.vue`.
=> [Nexus-1713] Test: BaseSettingsForm.vue

src/utils/__test__/FlowPreview.spec.js
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1722] Add initial tests flowPreview

src/__tests__/integration/brain.integration.test.js
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1730] Add initial brain integration tests

src/__tests__/components/actions/ModalChangeAction.spec.js, src/__tests__/views/Brain/Brain.spec.js, src/components/repository/IntegrateNotification.vue, src/components/repository/__tests__/IntegrateNotification.unit.spec.js, src/components/repository/home/HomeRepositoryCard.vue, src/components/repository/home/HomeRepositoryCardFooter.vue, src/components/repository/home/IntelligenceFromProjectItem.vue, src/components/repository/home/ModalContainer.vue, src/components/repository/home/ModalDeleteContentIntelligence.vue, src/components/repository/home/__tests__/HomeRepositoryCard.unit.spec.js, src/components/repository/home/__tests__/HomeRepositoryCardFooter.unit.spec.js, src/components/repository/home/__tests__/ModalDeleteContentIntelligence.unit.spec.js, src/locales/en.json, src/views/Brain/Brain.vue, src/views/repository/content/Bases.vue
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
* Refactors and its unit tests `HomeRepositoryCard.vue`;
* Fixes broken test CI.
=> [Nexus-1701][Nexus-1746] Test: HomeRepositoryCard.vue and Refactoring

src/__tests__/views/NotFound.spec.js, src/__tests__/views/__snapshots__/NotFound.spec.js.snap
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1752] - Add notFound unit tests

src/__tests__/router/router.spec.js
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1753] - Add router unit tests

src/utils/FlowPreview.js, src/utils/__test__/FlowPreview.spec.js
* * [X] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1750] - Unit test completion FlowPreview

src/views/ContentBases/__tests__/filesPagination.unit.spec.js, src/views/ContentBases/__tests__/sitesPagination.unit.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
* Adds `sitesPagination.js` and `filesPagination.js` composables unit tests.
=> [Nexus-1773] Tests: FilesPagination.js and SitesPagination.js

src/utils/HotjarIdentifyUser.js, src/utils/__test__/HotjarIdentifyUser.unit.spec.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Waits untill the Hotjar function is active to send the user data.
=> [Nexus-1774] Bug: Wait Until the Hotjar Function is Active to Send the User Data

src/__tests__/integration/brain.integration.test.js, src/components/actions/ModalRemoveAction.vue, src/components/actions/steps/NominateAction.vue, src/views/Brain/RouterCustomization.vue, src/views/repository/content/BasesFormGenericList.vue
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1749] - Add ModalActions create integration tests

src/__tests__/integration/brain.integration.test.js, src/views/Brain/RouterContentBase.vue, src/views/repository/content/BarAddSite.vue, src/views/repository/content/BasesFormGenericListHeader.vue
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [NEXUS-1783] Add content base integration tests

src/__tests__/views/Brain/RouterTunings.spec.js, src/views/Brain/RouterTunings.vue
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
- fix bug
- add new logic label
=> Fix Label logic in config brain

src/__tests__/views/Brain/RouterTunings.spec.js, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/views/Brain/RouterTunings.vue
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
- strategic adjustments aimed at making it easier for users to use rather than confusing them 
- remove advanced settings 
- remove weniGpt
- adjust tests
=> [NEXUS-1851] - Brain - Redesign of the settings screen      

src/__tests__/integration/brain.integration.test.js, src/__tests__/views/Brain/RouterContentBase.spec.js, src/components/Brain/ContentBase/ContentItem.vue, src/components/Brain/ContentBase/ContentList.vue, src/components/Brain/ContentBase/ModalAddSite.vue, src/components/Brain/ContentFiles.vue, src/components/Brain/ContentSites.vue, src/components/Brain/ContentText.vue, src/components/Brain/__tests__/ContentFiles.spec.js, src/components/actions/ModalActions.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/views/Brain/Brain.vue, src/views/Brain/RouterContentBase.vue, src/views/ContentBases/pagination.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
New design content base page
- new components and new tests
- [Design File](https://www.figma.com/design/5E67hPt0HlCDckwCtnn1HR/Brain-Vision?node-id=127-484&m=dev)
=> [NEXUS-1838] New design content base page

src/components/Brain/ContentBase/ModalAddSite.vue, src/components/Brain/ContentBase/__tests__/ContentItem.spec.js, src/components/Brain/ContentBase/__tests__/ContentList.spec.js, src/components/Brain/ContentBase/__tests__/ModalAddSite.spec.js, src/components/Brain/ContentSites.vue, src/components/Brain/__tests__/ContentSites.spec.js, src/components/Brain/__tests__/ContentText.spec.js
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [Nexus 1883] - Unit Tests base content - Brain

src/components/Brain/BrainSideBar.vue, src/components/Brain/ContentBase/ContentItem.vue, src/components/Brain/ContentBase/ContentList.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Pagination would stop at a certain number of loaded items.
* Fixes bug pagination.
=> [Nexus-1902] Bug: Content List Pagination

src/api/nexus/Actions.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Fixes language in Actions.
=> [Nexus-1949] Actions: Language Adjustment

src/components/Brain/ContentFiles.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- correction of inconsistencies
adjusting on remove logic
adjusting columns list
=> [NEXUS-1951] - Adjust content base file logic

src/__tests__/api/nexusaiAPI.spec.js, src/__tests__/components/actions/ModalActions.spec.js, src/__tests__/components/actions/ModalChangeAction.spec.js, src/__tests__/integration/brain.integration.test.js, src/__tests__/views/Brain/Brain.spec.js, src/__tests__/views/Brain/RouterActions.spec.js, src/components/Brain/ContentBase/__tests__/ContentItem.spec.js, src/components/repository/home/__tests__/HomeRepositoryCard.unit.spec.js, src/views/repository/content/__tests__/BasesFormFilesItem.unit.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
* Fixes broken tests.
=> [Nexus-1949] Tests: Fix Broken Tests

src/components/Brain/ContentBase/ModalAddSite.vue, src/components/Brain/ContentBase/__tests__/ModalAddSite.spec.js
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
- fix alert translation
- adjusting translation
=> [NEXUS-1981] - Fix translation alert add sites

src/components/Markdown.vue
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
- Fix break lines in preview
- add logic to break lines in markdown
=> [Nexus 1986] - Add break line in markdown component

src/locales/en.json, src/locales/es.json, src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- adjusting translations
=> [Nexus 1987] - adjust translations actions

src/components/Brain/BrainHeaderPreview.vue, src/components/Brain/BrainWarningBar.vue, src/components/Brain/__tests__/BrainHeaderPreview.spec.js, src/components/Brain/__tests__/BrainWarningBar.spec.js, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/views/Brain/Brain.vue, src/views/Brain/RouterTuningsAdvanced.vue, src/views/repository/content/Tests.vue
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
- New logic BrainOn/BrainOff to help users
- refactoring header preview logic
- adding BrainOn/BrainOff logic in preview
- [Design File](https://www.figma.com/design/5E67hPt0HlCDckwCtnn1HR/Brain-Vision?node-id=851-1530&m=dev)
=> [Nexus 1932] - Adjust BrainOn/BrainOff on the Brain home screen       

src/locales/en.json, src/locales/es.json, src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- Change translations
- Change translations
=> [NEXUS-2019] - Adjusting brain translations

src/components/Brain/BrainWarningBar.vue, src/views/Brain/RouterTuningsAdvanced.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- Change  font-size and icon-size
- adjusting font-size and icon-size BrainWarningBar
=> [NEXUS-2019] - adjust font-size and icon-size BrainWarningBar

src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/views/Brain/Brain.vue, src/views/repository/content/Tests.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- [Design File 1](link_to_design_file_1)
=> [Nexus-2018] add export conversations preview in staging

src/utils/changeNameUtils.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- [Design File 1](link_to_design_file_1)
=> refcatoring changeNameUtils

src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/views/Brain/Brain.vue, src/views/repository/content/Tests.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- option to users get preview messages
- add logic to export messages
- add emit logic in Test component
- [Design File](https://www.figma.com/design/5E67hPt0HlCDckwCtnn1HR/Brain-Vision?node-id=697-825&t=YnRQBIlwl4o8UES1-1)
=> [NEXUS-2018] add export conversations in preview - Brain

src/components/Brain/Tunings/ChangesHistory.vue, src/utils/changeNameUtils.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- [Design File 1](link_to_design_file_1)
=> Feature/change history adjust data STAGING

src/components/Brain/Tunings/ChangesHistory.vue, src/utils/changeNameUtils.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- adjust for render correct values
- adding logic to verify text.new
=> [NEXUS-1933] - Adjust logic content text in recent activities

src/views/Brain/RouterTunings.vue
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
- non-synchronization of Brain_on status
- adding props data to RouterTunnings
=> [NEXUS-1933] - Fix advanced options state

src/utils/changeNameUtils.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
=> add new params in changeNameUtils

src/views/repository/content/MessageInput.vue, src/views/repository/content/__tests__/MessageInput.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Cover the agent builder preview with tests.
- Added tests at MessageInput.
=> [NEXUS-2095] - Preview medias tests

src/api/nexus/Actions.js, src/components/actions/ModalActionTypeSelector.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/utils/index.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
The agent builder will now make the media and location action available for the user to test their agent when they receive this action.
- Added medias and location as a type of action;
- Added medias and location translations.
- [Design File 1](https://www.figma.com/design/5E67hPt0HlCDckwCtnn1HR/Brain-Vision?node-id=824-1300&m=dev)
=> [NEXUS-2052] - Action type "Media and Location"

src/locales/en.json
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Medias and location action translation its broken.
- Added medias and location translation to english.
=> [NEXUS-2117] - Fix translation medias and location

.github/workflows/crowdin-download.yaml, .github/workflows/crowdin-upload.yaml, crowdin.yml
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Improve the application localization.
- Configured crowdin translation files;
- Configured crowdin workflows.
=> [NEXUS-2090] - Crowdin config

.github/workflows/crowdin-download.yaml, .github/workflows/crowdin-upload.yaml, crowdin.yml, src/locales/en.json
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Improve the application localization.
- Configured download translations at Crowdin to every day at 20pm;
- Adjusted crowdin translation files path.
=> [NEXUS-2090] - Fix Crowdin config

package.json, src/__tests__/components/actions/ModalChangeAction.spec.js, src/components/repository/CreateRepository/__tests__/IntelligenceTab.spec.js, src/views/repository/content/MessageInput.vue, src/views/repository/content/__tests__/MessageInput.spec.js, yarn.lock
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Users needed a audio preview to test their intelligent agents.
- Uncommented preview audio logic;
- Updated Unnnic version;
- Fixed unnnic failed form components tests;
- Fixed preview send audio on discard button.
https://github.com/user-attachments/assets/ced08a13-1546-404a-9a50-f27eb53b3e8c
=> [NEXUS-2126] - Audio at preview agent

src/components/Brain/BrainHeader.vue, src/components/Brain/BrainSideBar.vue, src/composables/useBrainRoutes.js, src/utils/index.js, src/views/Brain/Brain.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The translation of the agent builder route descriptions was not matching the user's locale, because the description translation method was not dynamic.
Moved the brain routes informations to a composable, so that this translation is dynamic, using the computed function.
=> [NEXUS-2256] - Fix views headers description translations

src/__tests__/api/nexus/monitoring.unit.spec.js, src/__tests__/views/Brain/RouterMonitoring/ReceivedMessages.spec.js, src/__tests__/views/Brain/RouterMonitoring/ReceivedMessagesHistory.spec.js, src/__tests__/views/Brain/RouterMonitoring/ReceivedMessagesHistoryQuestionAndAnswer.spec.js, src/store/__tests__/Monitoring.unit.spec.js, src/views/Brain/RouterMonitoring/RouterMonitoringReceivedMessagesHistory/QuestionAndAnswer.vue, src/views/Brain/RouterMonitoring/RouterMonitoringReceivedMessagesHistory/index.vue
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Keep test coverage above 70% and ensure that the monitoring messages history feature is covered by tests.
- Added monitoring messages history tests.
=> [NEXUS-2225] - Monitoring messages history tests

src/__tests__/views/Brain/RouterMonitoring/ReceivedMessagesHistoryQuestionAndAnswer.spec.js, src/api/nexus/Monitoring.js, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/store/Monitoring.js, src/views/Brain/RouterMonitoring/RouterMonitoringReceivedMessagesHistory/MessageContext.vue, src/views/Brain/RouterMonitoring/RouterMonitoringReceivedMessagesHistory/QuestionAndAnswer.vue, src/views/Brain/RouterMonitoring/RouterMonitoringReceivedMessagesHistory/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Users need to see context of the agent builder responses;
Added monitoring load message context and uncommented button to load the context.
- [Loaded context of monitoring messages](https://www.figma.com/design/5E67hPt0HlCDckwCtnn1HR/Brain-Vision?node-id=1588-4519&m=dev)
=> [NEXUS-2270] - Monitoring messages context

src/components/Brain/BrainSideBar.vue
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release monitoring for only weni users to test before releasing to everyone.
Added validation to release the monitoring page if the user's email contains `@weni.ai`.
=> [NEXUS-2319] - Unlock monitoring view to weni users

src/store/Monitoring.js, src/views/Brain/RouterMonitoring/RouterMonitoringReceivedMessages.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Some bugs were occurring in monitoring.
- Fixed a loop when clicking on the response to inspect before the previous request finishes;
- Fixed the minimum table size;
- Fixed the translation of tags when changing languages.
=> [NEXUS-2317] - Hotfix monitoring bugs

src/locales/en.json, src/locales/es.json, src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Some translations in the monitoring and send llm response to flow features were wrong.
Adjusted translations of mentioned features.
=> [NEXUS-2357] - Fix translations at monitoring and send llm response to flow

src/views/repository/content/Tests.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
AI's large token preview was breaking the preview layout.
- Added hidden overflow to the token preview container.
=> [NEXUS-2392] - Overflow at preview token

src/__tests__/api/nexus/monitoring.unit.spec.js, src/api/nexus/Monitoring.js, src/components/Brain/BrainHeader.vue, src/components/Brain/Monitoring/ViewFilter.vue, src/components/Brain/Monitoring/__tests__/ViewFilter.spec.js, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/store/Monitoring.js, src/store/__tests__/Monitoring.unit.spec.js, src/views/Brain/RouterMonitoring/RouterMonitoringPerformance.vue, src/views/Brain/RouterMonitoring/RouterMonitoringReceivedMessages/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Users need to filter messages coming from the preview or communication channels.
- Created monitoring view filter component and added to brain header;
- Added new parameter source for monitoring requests.
- [Design](https://www.figma.com/design/5E67hPt0HlCDckwCtnn1HR/Brain-Vision?node-id=2999-3742&t=F8xqn0Tv4sz7j7kU-1)
=> [NEXUS-2540] - Supervisor view filter

src/components/Brain/BrainHeader.vue, src/components/Brain/Preview/PreviewDetails.vue, src/components/Brain/Preview/PreviewDrawer.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Users need to be more aware of what is happening during the multi-agent flow
- Add preview button for agents team route
- Implement agents preview drawer with visual flow and logs tabs
- [Design](https://www.figma.com/design/FGfl8EmJCNMz45TX1s3XQO/Agents-Builder-2.0?node-id=788-194&m=dev)
=> [NEXUS-2590] - Drawer of agents team preview

src/__tests__/views/Brain/RouterAgentsTeam/ActiveTeam.spec.js, src/__tests__/views/Brain/RouterMonitoring/index.spec.js, src/api/nexus/AgentsTeam.js, src/components/Brain/BrainHeader.vue, src/components/Brain/Preview/AgentCard.vue, src/components/Brain/Preview/PreviewDetails.vue, src/components/Brain/Preview/PreviewDrawer.vue, src/components/Brain/Preview/PreviewLogsDetailsModal.vue, src/components/Brain/Preview/PreviewVisualFlow.vue, src/components/Brain/PreviewLogs.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/store/Preview.js, src/views/Brain/RouterAgentsTeam/ActiveTeam.vue, src/views/Brain/RouterMonitoring/index.vue, src/websocket/__tests__/socket.unit.spec.js, src/websocket/listeners/index.js, src/websocket/listeners/preview/addTrace.js, src/websocket/listeners/preview/index.js, src/websocket/setup.js, src/websocket/socket.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Users need to be more aware of what is happening during the multi-agent flow
- Created PreviewLogs component;
- Implement WebSocket preview logs and trace handling;
- [Design](https://www.figma.com/design/FGfl8EmJCNMz45TX1s3XQO/Agents-Builder-2.0?node-id=788-194&m=dev)
=> [NEXUS-2590] - Logs streamed of agents team preview

src/api/nexus/AgentsTeam.js, src/components/Brain/Preview/AgentCard.vue, src/components/Brain/Preview/BranchLines.vue, src/components/Brain/Preview/PreviewDetails.vue, src/components/Brain/Preview/PreviewVisualFlow.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/store/Preview.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Users need to be more aware of what is happening during the multi-agent flow
- Created VisualFlow and BranchLines component and added to agents team preview.
- [Design](https://www.figma.com/design/FGfl8EmJCNMz45TX1s3XQO/Agents-Builder-2.0?node-id=788-194&m=dev)
=> [NEXUS-2594] - Visual flow of agents team preview 

src/components/Brain/Preview/PreviewVisualFlow.vue, src/views/repository/content/Tests.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Some experience improvements could be improved in the preview.
- Improve visual flow height reactivity in PreviewVisualFlow
- Fix text wrapping in test details view
=> [NEXUS-2605] - Adjusts at preview UX

src/assets/icons/BranchLines.vue, src/assets/icons/__tests__/BranchLines.spec.js, src/components/Brain/Preview/PreviewAgentCard.vue, src/components/Brain/Preview/PreviewDetails.vue, src/components/Brain/Preview/PreviewDrawer.vue, src/components/Brain/Preview/PreviewLogsDetailsModal.vue, src/components/Brain/Preview/PreviewVisualFlow.vue, src/components/Brain/Preview/__tests__/PreviewAgentCard.spec.js, src/components/Brain/Preview/__tests__/PreviewDetails.spec.js, src/components/Brain/Preview/__tests__/PreviewDrawer.spec.js, src/components/Brain/Preview/__tests__/PreviewLogsDetailsModal.spec.js, src/components/Brain/Preview/__tests__/PreviewVisualFlow.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
A multi-agent visualization feature was developed without testing, remaining as a technical subsidy.
Added some tests for the muilti agents preview feature.
=> [NEXUS-2604] - Some tests of new preview

src/api/nexusaiAPI.js, src/components/Brain/AgentsTeam/AssignAgentCard.vue, src/components/Brain/AgentsTeam/AssignAgentDrawer.vue, src/components/Brain/AgentsTeam/__tests__/__snapshots__/AssignAgentCard.spec.js.snap, src/components/Brain/Tunings/Credentials/CredentialsForm.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/store/Tunings.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
=> [NEXUS-2650] - Enhance agent credentials management and handling

src/api/nexus/AgentsTeam.js, src/components/Brain/AgentsTeam/AssignAgentCard.vue, src/components/Brain/AgentsTeam/AssignAgentDrawer.vue, src/components/Brain/BrainHeader.vue, src/components/Brain/Preview/PreviewDrawer.vue, src/components/Brain/Preview/__tests__/PreviewDrawer.spec.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
After releasing the Beta version of Agent Builder 2.0, we identified some improvements to the UX, such as a loading state when removing agents in the active agents tab, hiding sensitive information when assigning an agent with credentials, and maintaining the websocket connection and traces even if the preview drawer is closed.
- Add loading state for agent assignment toggle;
- Hide generic error alert during agent assignment, avoid duplicated alerts;
- Add password input type for confidential credentials at AssignAgentDrawer;
- Replaced WebSocket connection management from PreviewDrawer to BrainHeader.
=> [NEXUS-2728] - Improvements of Agent Builder 2.0

src/composables/useIntelligences.js, src/views/Home.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The content intelligence listing request was calling the wrong endpoint.
- Implemented loadContentIntelligences function to fetch content intelligences from NexusAI API;
- Some unnecessary code redundancies have also been removed from functions that require intelligence.
=> [NEXUS-2775] - Fix content intelligences fetch

src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/store/Profile.js, src/store/__tests__/Profile.unit.spec.js, src/views/Brain/RouterProfile/RouterProfileHumanSupport.vue, src/views/Brain/RouterProfile/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Agents need to activate a human service route from a prompt in Agent Builder 2.0
- Add human support feature with localization and profile management to AB2.
=> [NEXUS-2776] - Human support at Agent Builder 2.0

.github/workflows/build-ia-frontend-push-tag-shared.yaml
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
change workflow to reusable-workflow
- [Design File 1](link_to_design_file_1)
=> change workflow to reusable-workflow

src/api/adapters/tunings/progressiveFeedback.js, src/api/nexusaiAPI.js, src/components/Brain/BrainHeader.vue, src/components/Brain/Tunings/SettingsAgentsTeam/AgentsPreview.vue, src/components/Brain/Tunings/SettingsAgentsTeam/index.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/store/Tunings.js, src/views/Brain/RouterTunings.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Agent Builder 2.0 users need an option to improve response latency.
- Added the settings tab for projects with access to Agent Builder 2.0
- Added logic to load and edit agent settings
- Added logic to save edits to the tunings tab, separating credential requests and settings.
- [Design File](https://www.figma.com/design/FGfl8EmJCNMz45TX1s3XQO/Agents-Builder-2.0?node-id=2400-3271)
=> [NEXUS-2812] - Agents settings

src/store/Profile.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- Improve experience user on active/inative human service
- add new human service status event
=> [ENGAGE-3409] add new human service status event

src/__tests__/router/router.spec.js, src/main.js, src/router/index.js, src/utils/jwt.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
A security flaw was found in the way the authentication token is passed to microfrontends.
- Integrate JWT token retrieval before initializing the app;
- Add external login route without token, only org and project handling;
=> [NEXUS-2841] - JWT by window event

src/api/adapters/tunings/components.js, src/api/nexusaiAPI.js, src/components/Brain/BrainHeader.vue, src/components/Brain/Tunings/SettingsAgentsTeam/AgentsPreview.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/store/Tunings.js, src/views/Brain/RouterTunings.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Some Agent Builder 2.0 projects prefer to disable multiple message formatting (components)
Added components management at Agent Builder 2.0 settings
- [Design File](https://www.figma.com/design/FGfl8EmJCNMz45TX1s3XQO/Agents-Builder-2.0?node-id=2400-3298&m=dev)
=> [NEXUS-2879] - Added components management to Agent Builder 2.0 settings

src/components/Brain/Tunings/SettingsAgentsTeam/AgentsPreview.vue, src/components/Brain/Tunings/SettingsAgentsTeam/SettingsField.vue, src/store/Tunings.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
This feature aims to enable progressive feedback from the agent so that end users experience less latency.
Implement progressive feedback management in Tunings AgentsPreview component.
=> [NEXUS-2929] - Added progressive feedback management to Agent Builder 2.0 settings

package.json, src/components/Brain/Preview/Particles.vue, src/components/Brain/Preview/PreviewAgentCard.vue, src/components/Brain/Preview/PreviewVisualFlow.vue, src/components/Brain/Preview/__tests__/PreviewAgentCard.spec.js, src/components/Brain/Preview/__tests__/PreviewVisualFlow.spec.js, src/main.js, yarn.lock
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
To improve the user experience, more animations were requested to indicate active agents.
- Integrate particles effect in PreviewAgentCard and create Particles component;
- Added `tsparticles` lib;
- Changed the manager current task to empty instead "Coordinating team tasks".
- [Design File](https://www.figma.com/design/FGfl8EmJCNMz45TX1s3XQO/Agents-Builder-2.0?node-id=3225-1248&m=dev)
https://github.com/user-attachments/assets/10b0bc7a-da8c-447d-9b3e-e345c9024c1b
=> [NEXUS-3110] - Preview agents animation

src/components/Brain/PreviewLogs.vue, src/components/MessageComponents/CtaMessage.vue, src/components/MessageComponents/MessageComponentResolver.vue, src/components/MessageComponents/__tests__/CtaMessage.spec.js, src/components/MessageComponents/__tests__/MessageComponentResolver.spec.js, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/utils/previewLogs.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Supervisor message logs were not loading when model components were enabled. Also, CTA Message was not working correctly in preview.
- Fixed loading of logs with supervisor traces when model components are enabled.
- Updated the format of objects expected by the CTA Message component to follow the standard sent by the model.
- Added handling for the postProcessingTrace trace.
=> [NEXUS-3144] - Hotfix preview CTA component and Supervisor with components

src/main.js, src/utils/plugins/Hotjar.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The application was not initiating a connection with Hotjar
Adjusted hotjar script to init immediatly
=> [NEXUS-3168] - Fix Hotjar

src/components/Brain/Tunings/SettingsAgentsTeam/AgentsPreview.vue, src/components/Brain/Tunings/SettingsAgentsTeam/HumanSupport.vue, src/components/Brain/Tunings/SettingsAgentsTeam/SettingsField.vue, src/components/Brain/Tunings/SettingsAgentsTeam/__tests__/AgentsPreview.spec.js, src/components/Brain/Tunings/SettingsAgentsTeam/__tests__/HumanSupport.spec.js, src/components/Brain/Tunings/SettingsAgentsTeam/__tests__/SettingsField.spec.js, src/components/Brain/Tunings/SettingsAgentsTeam/__tests__/index.spec.js, src/components/Brain/Tunings/SettingsAgentsTeam/index.vue, src/views/AgentBuilder/Supervisor/SupervisorConversations/Conversation/QuestionAndAnswer/Message.vue, src/views/AgentBuilder/Supervisor/SupervisorConversations/Conversation/QuestionAndAnswer/__tests__/Message.spec.js, src/views/AgentBuilder/Supervisor/SupervisorConversations/Conversation/QuestionAndAnswer/__tests__/index.spec.js, src/views/AgentBuilder/Supervisor/SupervisorConversations/Conversation/QuestionAndAnswer/index.vue
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Increase application test coverage
Add tests at SettingsField, AgentsPreview, HumanSupport, SettingsAgentTeam, Message and QuestionAndAnswer components.
=> [NEXUS-3187] - Encrease tests coverage

src/__tests__/store/Project.unit.spec.js, src/store/Tunings.js, src/store/__tests__/Supervisor.unit.spec.js, src/store/__tests__/Tunings.unit.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Encrease application tests coverage
- Add unit tests for Tunings store
- Enhance Supervisor store unit tests
=> [NEXUS-3224] - Encrease tests to Agent Builder 2.0 stores

src/store/Supervisor.js, src/store/__tests__/Supervisor.unit.spec.js, src/views/AgentBuilder/Supervisor/SupervisorConversations/Conversation/__tests__/index.spec.js, src/views/AgentBuilder/Supervisor/SupervisorConversations/ConversationsTable/ConversationsSearch.vue, src/views/AgentBuilder/Supervisor/SupervisorConversations/ConversationsTable/__tests__/ConversationsSearch.spec.js, src/views/AgentBuilder/Supervisor/SupervisorConversations/ConversationsTable/__tests__/index.spec.js, src/views/AgentBuilder/Supervisor/SupervisorConversations/ConversationsTable/index.vue, src/views/AgentBuilder/Supervisor/SupervisorHeader.vue, src/views/AgentBuilder/Supervisor/__tests__/SupervisorHeader.spec.js, src/views/AgentBuilder/Supervisor/__tests__/SupervisorPerformance.unit.spec.js, src/views/AgentBuilder/Supervisor/index.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The Supervisor was made with a filter management in the query param, but they were not reflected in the view. This PR fixes that.
- Fix initial states to Supervisor filters based on route;
- Added contactUrn filter as query param.
=> [NEXUS-3243] - Enhance Supervisor view with route-based filters

src/api/adapters/supervisor/conversation.js, src/api/nexus/Supervisor.js, src/components/AgentBuilder/Supervisor/SupervisorHeaderDetails.vue, src/components/Markdown.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/router/index.js, src/store/Supervisor.js, src/store/__tests__/Supervisor.unit.spec.js, src/views/AgentBuilder/OldSupervisor/index.vue, src/views/AgentBuilder/Supervisor/SupervisorConversations/Conversation/index.vue, src/views/AgentBuilder/Supervisor/SupervisorConversations/ConversationsTable/ConversationRow.vue, src/views/AgentBuilder/Supervisor/SupervisorConversations/ConversationsTable/__tests__/index.spec.js, src/views/AgentBuilder/Supervisor/SupervisorConversations/ConversationsTable/index.vue, src/views/AgentBuilder/Supervisor/SupervisorConversations/index.vue, src/views/AgentBuilder/Supervisor/SupervisorFilters/index.vue, src/views/AgentBuilder/Supervisor/__tests__/__snapshots__/index.spec.js.snap, src/views/AgentBuilder/Supervisor/index.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Supervisor bug fixes and visual adjustments necessary to improve the user experience.
- Adjusted the Supervisor's filter section to support up to 4 filters on the same line;
- Added missing translations and removed those no longer used;
- Fixed the filter request logic in Supervisor and implemented a request abort to avoid asynchronous issues with multiple calls;
- Fixed the AvatarLetter prop in Conversation;
- Adjusted the scroll behavior responsible for conversation pagination;
- Removed the conversation count paragraph while the endpoint undergoes optimization.
- Changed conversation statuses from "Resolved" to …
=> [NEXUS-3655] - Adjusts at new Supervisor

src/composables/useBrainRoutes.js, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/router/index.js, src/views/AgentBuilder/Instructions/__tests__/Instructions.spec.js, src/views/AgentBuilder/Instructions/__tests__/__snapshots__/Instructions.spec.js.snap, src/views/AgentBuilder/Instructions/index.vue, src/views/AgentBuilder/index.vue
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
New Instructions tab
- Added instructions to useBrainRoutes;
- Added instructions route and corresponding view component
- Added relative tests
- [Design File](https://www.figma.com/design/eNmMZGIiFg1nlKadJjc6tf/Instructions?node-id=6289-13052&m=dev)
=> [NEXUS-3697] - Instructions view
